---
- src: https://github.com/netology-code/mnt-homeworks-ansible.git
  scm: git
  version: "1.0.1"
  name: java

- src: https://github.com/Marinakrivitskaya/kibana-role.git
  scm: git
  version: "1.0.0"
  name: kibana-role

- src: https://github.com/Marinakrivitskaya/elastic-role.git
  scm: git
  version: "1.0.0"
  name: elastic-role
